### ISSUE TITLE
Specification for read-only (or const) defines

### ISSUE THREAD

**Issue by achilleas-k** [osbuild/otk#101]
While discussing the partition table generator with @mvo5, we considered the idea of having a way to signal that certain defines shouldn't be modified after they're set (even producing an error if they are).  This is especially important for large, complicated data structures generated by externals where there are interdependencies between values (like the partition table).

Consider the following scenario:
- The partition table external generates a fully-described PT structure (with UUIDs, starts and offets, etc) and stores it in `${filesystems}`
- A truncate stage is generated as:
```yaml
otk.target.osbuild:
pipeline:
 disk:
  - type: org.osbuild.truncate
    options:
      filename: "whatever.disk"
      size: ${filesystems.partition_table.size}
```
- The user decides to change the size of the partition table but due to a poor understanding of the mechanics of externals and defines, does the following:
```yaml
otk.define.defaults:
  filesystems:
    otk.external.gen_partition_table:
      ...
      size: "10 GiB"
      ...
  
  ...
  # potentially in a different file
  filesystems.partition_table.size: "20 GiB"

otk.target.osbuild:
pipeline:
 disk:
  - type: org.osbuild.truncate
    options:
      filename: whatever.disk
      size: ${filesystems.partition_table.size}
```

If this is allowed, it'll throw off the the partition table consistency and partition positions and alignments.  Changing other values could also make the whole thing unbuildable (which might be better or worse depending on POV).

It would be nice to have a way to _protect_ values inside data structures generated by externals in some way, perhaps with a keyword convention (`const`?).  So in the example above, the generator adds the `const` (or whatever) keyword to the data structure it produces, making the  property `${fileystems.const...}` and anything under `const` can't be modified after it's set the first time and doing:
```yaml
otk.define.stuff:
  filesystems.const.partition_table.size: "5 KiB"
```
produces an error.
