### ISSUE TITLE
Nested variable definitions, sub-variable references, and includes

### ISSUE THREAD

**Issue by achilleas-k** [osbuild/otk#116]
I came up with a fun little example of nested variable definitions and references:
```yaml
otk.version: "1"

otk.define.x:
  a: 1
  b:
    a: 2  # b.a
    outer: "${a}"  # 1
    inner: "${b.a}"  # 2


otk.target.osbuild.x:
  vars:
    - "{a}"  # 1
    - "{b}"  # { ... }
    - "{b.a}"  # 2
    - "{b.outer}"  # 1
    - "{b.inner}"  # 2
  ```

There's an interesting thing going on with the context that we need to be explicit about.  When resolving defines, we need to have the global defines available but ONLY for reading.  Because when we're defining the `b:` block of variables in this case, we want to be able to read the global, upper level value of `${a}`, but we should only be able to define keys under `b:`.  So `outer:` shouldn't be set in the global context, but a kind of sub-context that is nested under `b:`.
We could do this with some special handling of the context or we can consider the context "read only" while working on defines and then return the new values from the defines handler and set them externally, under the key we were processing.  But I think that wont work either, because the new defines should be available immediately as well (e.g. `${b.a}` is already defined when processing the value of `outer:`).

It might be easier to have direct access to the defines dict from the context here.  Because then we can do:
```python
new_block = context.defines.get("b", {})  # get the "b" block if it already exists so we can update it
define(context, tree["b"], new_block)  # runs through the "b" subtree populating new_block with new values and using context.defines for resolving references
context.defines["b"] = new_block  # set the new stuff under "b"
```

However, this whole thing brings up another interesting edge case when includes are thrown in the mix:
```yaml
otk.define.first:
  outer:
    a: 1
    otk.include: "other.yaml"

otk.define.second:
  otk.include: "other.yaml"

--- [other.yaml]
otk.define.other:
  a: 2
  b: "${a}"
```

If defines are really global, `b: ${a}` will be set to `1` in the first case and `2` in the second, because the meaning of `${a}` changes.  In the first case, `${a}` refers to the global defined in the first block and the other `a:` gets registered as `${outer.a}`.  In the second case, `a: 2` overrides the global `${a}` because the include is not nested.
This might be a problem because variables in includes will behave differently based on where the define is nested.  When writing an otk fragment, I would expect that:

```yaml
plat: "f38"
plat_long: "platform:${plat}"
```

will set `plat_long` to `platform:f38`, because _even if_ `${plat}` is defined before we include the fragment from an outer scope, the fragment is overriding it.  But that's not the case if the fragment is included in a subkey in a defines block.

**Comment by achilleas-k** [comment]
Perhaps include scopes are the solution here?  But that would change our general idea that "includes just replace objects", it would mean that:

```yaml
otk.define.first:
  outer:
    otk.include: "other.yaml"  # outer.a: 1, outer.b: 1

--- [other.yaml]
a: 1
b: "${a}"  # 1
```

Is not the same as:
```yaml
otk.define.first:
  outer:
    a: 1
    b: "${a}"  # error: a isn't set
```

Which might be ok in the end.
