### ISSUE TITLE
Review external/langauge support for arthimetic 

### ISSUE THREAD

**Issue by mvo5** [osbuild/otk#235]
We currently have: https://github.com/osbuild/otk/commit/9745d213d47f15eac07fb26a35f48f12db77a7bd#diff-25d48cd0a80de2fc2e346a35770961b580c16096f70463c0f8ea58a61a1eb0b0R8 

The rootfs for the iso installer is currently setup like this:
```yaml
otk.define:
  ...
  size_iso_efiboot: '20971520'
  size_iso_efiboot_in_sectors: 40960
```
where  size_iso_efiboot_in_sectors is just size_iso_efiboot / 512. So  think about something like:
1.  `${size_iso_efiboot / 512}` to avoid size_iso_efiboot_in_sectors *or*
2.  supporting "size_iso_efiboo` directly in the "truncate" stage (i.e. a new input like "size_in_byte") *or*
3. an external 
```yaml
otk.define:
 size_iso_efiboot: '20971520'
 otk.external.calc:
   define: size_iso_efiboot_in_sectors
   calc: ${size_iso_efiboot} / 512
```
(or something else)
