### ISSUE TITLE
Kernel name is currently hardcoded in otk files

### ISSUE THREAD

**Issue by mvo5** [osbuild/otk#239]
Currently the kernel pkgname is a mix of hardcoded and tweakable, e.g. from the centos-9-x86_64-qcow2.yaml:
```yaml

otk.version: "1"

otk.define:
...
    os:
      otk.external.osbuild-gen-depsolve-dnf4:
        architecture: x86_64
        module_platform_id: c9s
        releasever: "9"
        repositories:
          otk.include: "common/repositories/x86_64.yaml"
        packages:
          include:
...
            - kernel
  kernel:
...
    package:
      otk.external.osbuild-get-dnf4-package-info:
        packageset: ${packages.os}
        packagename: "kernel"
...
        - type: org.osbuild.sysconfig
          options:
            kernel:
....
              default_kernel: kernel
```
adding this so that we make sure to update this to full customizable
