### ISSUE TITLE
Multiple directives clash with previous directives

### ISSUE THREAD

**Issue by supakeen** [osbuild/otk#62]
When having multiple directives:

```yaml
otk.define:
  a: 1

otk.define:
  b: ${a}
```

Things go wrong. This is due to this being a mapping so duplicate keys at the same level are not allowed and have this behavior.

**Comment by supakeen** [comment]
This *could* be solved if we were to do: #47 however it would annoy things like `yamllint` which will error on duplicate keys.

**Comment by supakeen** [comment]
Note that doing this and processing duplicate keys would violate the principle of being valid YAML.

**Comment by supakeen** [comment]
Also it *is* possible to work around this:

```yaml
otk.define:
  otk.op.join:
    - my: name
      my: other
    - otk.include: common.yaml
```

For example. Not the prettiest but it is explicit.
