### ISSUE TITLE
Change `otk.meta.<*>`

### ISSUE THREAD

**Issue by supakeen** [osbuild/otk#85]
`otk.meta.<*>` won't be used. We will be using specific targets where `otk.define`d variables are used:

For example:

```yaml
otk.define:
 image.vdk.filename: "image.raw"  
 version: "9"
 distribution:      # Flo +1
   name: "CentOS"
   version: ${version}
   ...

otk.target.osbuild_manifest:
  pipelines:
    - ...

otk.target.osbuild_meta:
  ID: ${distribution.name}
  VERSION_ID: ${distribution.version}
```
